services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: productos_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    ports:
      - '5000:5000'
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DB=productos_db
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db
    restart: always

volumes:
  db_data:
